// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WiseHousingHub.Data;

#nullable disable

namespace WiseHousingHub.Migrations
{
    [DbContext(typeof(WiseContext))]
    [Migration("20240419183427_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("WiseHousingHub.Models.Landlord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Landlords");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "john@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            PhoneNumber = "123-456-7890"
                        },
                        new
                        {
                            Id = 2,
                            Email = "joet@aol.com",
                            FirstName = "Joe",
                            LastName = "Tester",
                            PhoneNumber = "555-744-3219"
                        },
                        new
                        {
                            Id = 3,
                            Email = "janesmith10@gmail.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            PhoneNumber = "713-210-1921"
                        });
                });

            modelBuilder.Entity("WiseHousingHub.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Bathrooms")
                        .HasColumnType("int");

                    b.Property<int>("Bedrooms")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateListed")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("Furnished")
                        .HasColumnType("bit");

                    b.Property<string>("ImageFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<int>("LandlordId")
                        .HasColumnType("int");

                    b.Property<string>("LeaseType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ParkingSpaces")
                        .HasColumnType("int");

                    b.Property<bool>("PetsAllowed")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("SquareFeet")
                        .HasColumnType("float");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WheelchairAccessible")
                        .HasColumnType("bit");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LandlordId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "9070 Robinette Cir",
                            Bathrooms = 3,
                            Bedrooms = 3,
                            City = "Wise",
                            DateListed = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Welcome home to this beautiful manufactured 3 bedroom, 3 bathroom well maintained property. The location of this rental offers tons of conveniences. It is located close to restaurants, shopping centers, and schools. This rental looks and smells brand new on the inside. It features an open floor plan with the living room, dining room, and kitchen close together. The living room features a beautiful fireplace with gas logs. The kitchen has tons of cabinets and  a bar area. The master bedroom is very spacious with a large walk-in closet, 2 master bathrooms, and sitting area. Two additional bedrooms with walk-in closets are located on the opposite side of the rental along with a third full bath. It also features a pantry and laundry room.",
                            Furnished = true,
                            ImageFileName = "blue_trailer.jpg",
                            IsVerified = true,
                            LandlordId = 1,
                            LeaseType = "1-Year",
                            ParkingSpaces = 2,
                            PetsAllowed = false,
                            Price = 900m,
                            SquareFeet = 1495.0,
                            State = "Virginia",
                            WheelchairAccessible = false,
                            Zip = "24293"
                        },
                        new
                        {
                            Id = 2,
                            Address = "9027 Camp Bethel Road",
                            Bathrooms = 1,
                            Bedrooms = 2,
                            City = "Wise",
                            DateListed = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Are you looking for a move in ready rental full of southern charm? With recent updates to include the windows, electrical, and roof you should have no worries! Beautiful hardwood flooring in the living room, sun room to enjoy your morning coffee, on over half an acre of land. Off to itself overlooking a horse pasture.",
                            Furnished = false,
                            ImageFileName = "green_house.jpg",
                            IsVerified = true,
                            LandlordId = 2,
                            LeaseType = "1-Year",
                            ParkingSpaces = 3,
                            PetsAllowed = true,
                            Price = 715m,
                            SquareFeet = 1309.0,
                            State = "Virginia",
                            WheelchairAccessible = false,
                            Zip = "24293"
                        },
                        new
                        {
                            Id = 3,
                            Address = "826 NE Hurricane Rd",
                            Bathrooms = 1,
                            Bedrooms = 3,
                            City = "Wise",
                            DateListed = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Check out this cottage-style rental with 3 bedroom and 1 bath that has been freshly remodeled. New roof, heat pump and kitchen makes this cozy little property stand out. The refurbished hard wood floors and freshly painted walls makes this rental ready to move right in. Located conveniently close to The University of Virginia's College at Wise and within walking distance to downtown Wise. Location and convenience makes this the rental for you. And the best part is out the back door just a few steps and cross the small bridge and across the creek you have a perfect place for a firepit and small gatherings.",
                            Furnished = false,
                            ImageFileName = "white_house.jpg",
                            IsVerified = true,
                            LandlordId = 2,
                            LeaseType = "6-Month",
                            ParkingSpaces = 1,
                            PetsAllowed = true,
                            Price = 790m,
                            SquareFeet = 1261.0,
                            State = "Virginia",
                            WheelchairAccessible = true,
                            Zip = "24293"
                        },
                        new
                        {
                            Id = 4,
                            Address = "6331 Stephens Rd",
                            Bathrooms = 2,
                            Bedrooms = 3,
                            City = "Wise",
                            DateListed = new DateTime(2024, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "This rental is 3 bed, 2 bath, and 1920 sq.ft. It has an open concept layout for main living area. Large kitchen with lots of oak cabinets, large island with built-in table, patio doors open onto small deck. Adjacent den has propane gas log fireplace. Formal dining room off the kitchen opens into a large living room. Large master suite with garden tub, stand up shower, large walk-in closet. Two additional bedrooms with separate full bath. Laundry room is located off kitchen/den area adjacent to back entrance. This property has a block perimeter. There is a large area fenced separately from the yard for dogs. The front yard has a nice stream that runs all year round.",
                            Furnished = false,
                            ImageFileName = "tan_doublewide.jpg",
                            IsVerified = true,
                            LandlordId = 1,
                            LeaseType = "1-Year",
                            ParkingSpaces = 3,
                            PetsAllowed = true,
                            Price = 820m,
                            SquareFeet = 1920.0,
                            State = "Virginia",
                            WheelchairAccessible = false,
                            Zip = "24293"
                        });
                });

            modelBuilder.Entity("WiseHousingHub.Models.Property", b =>
                {
                    b.HasOne("WiseHousingHub.Models.Landlord", "Landlord")
                        .WithMany("Properties")
                        .HasForeignKey("LandlordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Landlord");
                });

            modelBuilder.Entity("WiseHousingHub.Models.Landlord", b =>
                {
                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
